### ISSUE TITLE
How to fix it ...

### ISSUE THREAD

**Issue by Nobody20369** [cyberknight777/instashell#1]
![Screenshot_20201222_161837](https://user-images.githubusercontent.com/75668726/102880533-7cc1c900-4471-11eb-83c7-27f75c7e8a72.png)

**Comment by ranjan-del** [comment]
@cyberknight777 
![Screenshot_20201224-095242_Termux](https://user-images.githubusercontent.com/76397067/103060349-d212ed00-45cd-11eb-9c5f-44554c346f36.jpg)
Pls help to solve this

**Comment by cyberknight777** [comment]
Use my ver of instashell and also install its requirements

**Comment by ranjan-del** [comment]
I have installed u r version only bro 
How to solve this

**Comment by ranjan-del** [comment]
@cyberknight777 
Should i root my phone

**Comment by cyberknight777** [comment]
nou you didn't and stop trying to bruteforce Instagram it's useless

**Comment by ranjan-del** [comment]
@cyberknight777 
Why bro

**Comment by cyberknight777** [comment]
It's useless dude

**Comment by ranjan-del** [comment]
@cyberknight777 
Can i txt in telegram

**Comment by cyberknight777** [comment]
yes.

**Comment by ranjan-del** [comment]
@cyberknight777 
My telegram name is ranjan appu 
Pls reply
